apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sonarqube-test2
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
   # sonarqube.org/project-key: plp/backstage
   sonarqube.org/project-key: backdora_backdora
   # gitlab.com/project-id: "573"
spec:
  type: library
  owner: CNCF
  lifecycle: experimental

