apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: csd.pl.s2-eu.capgemini.com/sonarqube/3cd2eb98bd6773f96f8e1d3b4161956e9a95fda3
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
