apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: localhost:9000/sqp_1f6d9aa37278a65903c9bd0dc421876114ae19d2
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
