apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sonarqube-test
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
   sonarqube.logius.plp.cloud/project-key: backstage
   # sonarqube.org/project-key: backdora_backdora
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
